name: test-cov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install flake8
          pip install pytest
          pip install pytest-cov
          make install
      - name: Lint with flake8
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test
          
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: fefb0d7c207f59f9b988d1527e4ba2f45b76be4f9bd223990be49ef0a60ef0ba
        with:
          coverageCommand: make test
          debug: true